name: Build Node.js backend and deploy to AWS ECR
on:   
  push:
    branches: 
      - 'CB**'
      - prod
      - uat
      - main

  workflow_dispatch:
    inputs:
      environment:
         description: 'Please select the environment on which to run:'
         required: true
         default: 'dev'
         type: choice
         options:
          - dev
          - uat
          - prod

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:  
    - run: |
          echo "env.name: ${{ env.name }}"
      
  build_and_push:
    if: ${{ (github.event.inputs.environment == 'dev' || github.event.inputs.environment == 'uat' || github.event.inputs.environment == 'prod' || github.event_name == 'push') && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/uat' || github.ref == 'refs/heads/prod')}}
    runs-on: ubuntu-22.04
    environment:
      name: ${{ github.ref_name }}
#       url: "http://www.backend-dev.crankbit.com/health-check"
      
    steps:  
    - run: |
          eat main.txt
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "env.name: ${{ env.name }}"
          echo "github.event.inputs.environment: ${{ github.event.inputs.environment }}"
          echo "finished"
